"""물성 확장: property_definition·source·property_value

Revision ID: 888056f1c5b8
Revises: a72e1f3c8b90
Create Date: 2026-07-30 00:25:53.606761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db  # 커스텀 타입(UTCDateTime) 참조용.


# revision identifiers, used by Alembic.
revision: str = '888056f1c5b8'
down_revision: Union[str, Sequence[str], None] = 'a72e1f3c8b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('si_unit', sa.String(length=40), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_standard', sa.String(length=120), nullable=True),
    sa.Column('condition_axes', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("value_type IN ('numeric','vector','categorical','boolean')", name='ck_propdef_value_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=30), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('license', sa.String(length=80), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('journal','book','database','datasheet','computed','standard','web','other')", name='ck_source_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('property_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('property_key', sa.String(length=80), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('quality_tier', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_detail', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("method IN ('measured','handbook','datasheet','computed','estimated')", name='ck_propval_method'),
    sa.CheckConstraint('quality_tier BETWEEN 1 AND 5', name='ck_propval_tier'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_key'], ['property_definition.key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_value', schema=None) as batch_op:
        batch_op.create_index('ix_property_value_material_prop', ['material_id', 'property_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_value', schema=None) as batch_op:
        batch_op.drop_index('ix_property_value_material_prop')

    op.drop_table('property_value')
    op.drop_table('source')
    op.drop_table('property_definition')
    # ### end Alembic commands ###
