"""instrument catalog

Revision ID: 9d623ccf6364
Revises: 888056f1c5b8
Create Date: 2026-08-15 22:50:32.575272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db  # 커스텀 타입(UTCDateTime) 참조용.


# revision identifiers, used by Alembic.
revision: str = '9d623ccf6364'
down_revision: Union[str, Sequence[str], None] = '888056f1c5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('technique', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('doc_path', sa.String(length=300), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('thermal','mechanical','surface','chemical','particle','optical','electrical','ndt','reliability')", name='ck_instrument_category'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor', 'model', name='uq_instrument_vendor_model')
    )
    op.create_table('instrument_capability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('property_key', sa.String(length=80), nullable=False),
    sa.Column('technique', sa.String(length=120), nullable=False),
    sa.Column('standard', sa.String(length=120), nullable=True),
    sa.Column('range_min', sa.Float(), nullable=True),
    sa.Column('range_max', sa.Float(), nullable=True),
    sa.Column('range_unit', sa.String(length=40), nullable=True),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.String(length=80), nullable=True),
    sa.Column('temperature_min_k', sa.Float(), nullable=True),
    sa.Column('temperature_max_k', sa.Float(), nullable=True),
    sa.Column('specimen', sa.String(length=200), nullable=True),
    sa.Column('mapping_confidence', sa.String(length=10), nullable=False),
    sa.Column('source_detail', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mapping_confidence IN ('high','medium','low')", name='ck_capability_confidence'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_key'], ['property_definition.key'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'property_key', 'technique', name='uq_capability_triple')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument_capability')
    op.drop_table('instrument')
    # ### end Alembic commands ###
