"""initial schema

Revision ID: c0fac20ef805
Revises: 
Create Date: 2026-07-03 15:59:57.275513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db  # 커스텀 타입(UTCDateTime) 참조용.


# revision identifiers, used by Alembic.
revision: str = 'c0fac20ef805'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('material_code', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code')
    )
    op.create_table('specimen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('geometry_type', sa.String(length=20), nullable=False),
    sa.Column('gauge_length_m', sa.Float(), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('thickness_m', sa.Float(), nullable=True),
    sa.Column('diameter_m', sa.Float(), nullable=True),
    sa.Column('area0_m2', sa.Float(), nullable=False),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('standard', sa.String(length=30), nullable=True),
    sa.CheckConstraint("(geometry_type = 'flat' AND width_m IS NOT NULL AND thickness_m IS NOT NULL) OR (geometry_type = 'round' AND diameter_m IS NOT NULL)", name='ck_specimen_geometry_dims'),
    sa.CheckConstraint("geometry_type IN ('flat','round')", name='ck_specimen_geometry_type'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specimen_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=30), nullable=False),
    sa.Column('machine', sa.String(length=100), nullable=True),
    sa.Column('software', sa.String(length=100), nullable=True),
    sa.Column('source_format', sa.String(length=20), nullable=True),
    sa.Column('strain_source', sa.String(length=20), nullable=False),
    sa.Column('test_speed_m_s', sa.Float(), nullable=True),
    sa.Column('temperature_k', sa.Float(), nullable=True),
    sa.Column('tested_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('invalid_reason', sa.String(length=200), nullable=True),
    sa.CheckConstraint("strain_source IN ('extensometer','crosshead')", name='ck_test_strain_source'),
    sa.ForeignKeyConstraint(['specimen_id'], ['specimen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constitutive_fit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('rmse_pa', sa.Float(), nullable=True),
    sa.Column('n_points', sa.Integer(), nullable=True),
    sa.Column('fitted_at', app.db.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('youngs_modulus_pa', sa.Float(), nullable=True),
    sa.Column('yield_strength_pa', sa.Float(), nullable=True),
    sa.Column('uts_pa', sa.Float(), nullable=True),
    sa.Column('uniform_elongation', sa.Float(), nullable=True),
    sa.Column('fracture_elongation', sa.Float(), nullable=True),
    sa.Column('reduction_of_area', sa.Float(), nullable=True),
    sa.Column('strain_hardening_n', sa.Float(), nullable=True),
    sa.Column('strength_coeff_k_pa', sa.Float(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('extra_metrics', sa.JSON(), nullable=True),
    sa.Column('computed_at', app.db.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id')
    )
    op.create_table('raw_curve_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('n_points', sa.Integer(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('inline_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_curve_ref')
    op.drop_table('processed_result')
    op.drop_table('constitutive_fit')
    op.drop_table('test')
    op.drop_table('specimen')
    op.drop_table('material')
    # ### end Alembic commands ###
