"""viscoelastic: relax strain_source constraint

Revision ID: c7b6cca38dc2
Revises: c0fac20ef805
Create Date: 2026-07-07 12:15:06.256822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db  # 커스텀 타입(UTCDateTime) 참조용.


# revision identifiers, used by Alembic.
revision: str = 'c7b6cca38dc2'
down_revision: Union[str, Sequence[str], None] = 'c0fac20ef805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('strain_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('strain_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
